//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asdep.GestioneAnagraficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSICURATI
    {
        public int Id_Assicurato { get; set; }
        public string Ente { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public string Secondo_Nome { get; set; }
        public string Codice_fiscale_assicurato { get; set; }
        public string Luogo_nascita_assicurato { get; set; }
        public Nullable<System.DateTime> Data_nascita_assicurato { get; set; }
        public string Codice_fiscale_caponucleo { get; set; }
        public string CodiceLegame { get; set; }
        public System.DateTime Data_Effetto { get; set; }
        public string Indirizzo_residenza { get; set; }
        public string Localita_residenza { get; set; }
        public string Sigla_prov_residenza { get; set; }
        public string Cap_residenza { get; set; }
        public string IBAN { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public System.DateTime Data_inserimento { get; set; }
        public Nullable<System.DateTime> Data_ultimo_aggiornamento { get; set; }
        public Nullable<bool> Esportato { get; set; }
        public Nullable<System.DateTime> TimeStampGenerali { get; set; }
        public Nullable<bool> Match_compagnia { get; set; }
        public Nullable<bool> Con_Errori { get; set; }
        public Nullable<bool> CF_errato { get; set; }
        public Nullable<bool> Match_Asdep { get; set; }
        public Nullable<decimal> PremioVITA { get; set; }
        public Nullable<decimal> PremioLTC { get; set; }
        public Nullable<decimal> PremioRSMO { get; set; }
        public Nullable<int> Eta { get; set; }
        public Nullable<bool> Err_eta { get; set; }
        public string Convenzione { get; set; }
        public string Categoria { get; set; }
        public Nullable<bool> Esclusione_Pregresse { get; set; }
        public string Numero_Polizza { get; set; }
        public Nullable<System.DateTime> Data_cessazione { get; set; }
        public string Progressivo { get; set; }
        public string Matricola { get; set; }
    }
}
