//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asdep.GestioneAnagraficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenefitPackage
    {
        public string Polizza { get; set; }
        public string cCategoria { get; set; }
        public bool bCaponucleo { get; set; }
        public bool bFiscalmente_a_carico { get; set; }
        public string cBenefitPackage { get; set; }
    }
}
