//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asdep.GestioneAnagraficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTI
    {
        public string CodiceEnte { get; set; }
        public string Descrizione { get; set; }
        public string DecorrenzaCopertura { get; set; }
        public Nullable<System.DateTime> DataCessazione { get; set; }
        public Nullable<System.DateTime> DataRiapertura { get; set; }
        public string Provincia { get; set; }
        public Nullable<decimal> IdEnte { get; set; }
        public string Certificato { get; set; }
    }
}
