//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asdep.GestioneAnagraficeDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASSICURATI_ASDEPEntities : DbContext
    {
        public ASSICURATI_ASDEPEntities()
            : base("name=ASSICURATI_ASDEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALTRE_CATEGORIE_2017> ALTRE_CATEGORIE_2017 { get; set; }
        public DbSet<ASSICURATI> ASSICURATI { get; set; }
        public DbSet<BenefitPackage> BenefitPackage { get; set; }
        public DbSet<ENTI> ENTI { get; set; }
        public DbSet<FNAC_DIPENDENTI_2017> FNAC_DIPENDENTI_2017 { get; set; }
        public DbSet<FNAC_DIPENDENTI_2017_2> FNAC_DIPENDENTI_2017_2 { get; set; }
        public DbSet<LEGAMI> LEGAMI { get; set; }
        public DbSet<SUPERQUERY> SUPERQUERY { get; set; }
        public DbSet<TIPI_ERRORI> TIPI_ERRORI { get; set; }
        public DbSet<VOLONTARIE_ALTRE_CATEGORIE_2017> VOLONTARIE_ALTRE_CATEGORIE_2017 { get; set; }
    }
}
