//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asdep.GestioneAnagraficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEGAMI
    {
        public string CodiceLegame { get; set; }
        public string DescrizioneLegame { get; set; }
        public Nullable<bool> Fiscalmente_a_Carico { get; set; }
        public Nullable<bool> Caponucleo { get; set; }
        public string CodiceCapoNucleo { get; set; }
        public Nullable<int> Eta_min { get; set; }
        public Nullable<int> Eta_max { get; set; }
    }
}
