//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asdep.GestioneAnagraficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPERQUERY
    {
        public string CODICE_FISCALE { get; set; }
        public string Tipo_Record { get; set; }
        public string parentela { get; set; }
        public string Codice_fiscale_caponucleo { get; set; }
        public string Codice_fiscale_assicurato { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public string sesso { get; set; }
        public string data_di_nascita { get; set; }
        public string Comune { get; set; }
        public string Provincia { get; set; }
        public string Indirizzo { get; set; }
        public string cap { get; set; }
        public string città { get; set; }
        public string Expr1 { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string dataingressoinpolizza { get; set; }
        public Nullable<System.DateTime> data_uscita_polizza { get; set; }
        public string IBAN { get; set; }
        public string Den_intestatario_conto { get; set; }
        public string Opzione { get; set; }
        public string data_modifica_opzione { get; set; }
        public string presenza_integrativa { get; set; }
        public string presenza_LTC { get; set; }
        public string Numero_Polizza { get; set; }
        public string Categoria { get; set; }
        public string Convenzione { get; set; }
        public string Ente { get; set; }
    }
}
