//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asdep.GestioneAnagraficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPI_ERRORI
    {
        public string CodiceErrore { get; set; }
        public string DescrizioneErrori { get; set; }
    }
}
