//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asdep.GestioneAnagraficeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOLONTARIE_ALTRE_CATEGORIE_2017
    {
        public string PARTITA_IVA_AZIENDA { get; set; }
        public string TIPO_RECORD { get; set; }
        public string PARENTELA { get; set; }
        public string CODICE_FISCALE { get; set; }
        public string CODICE_FISCALE_CAPONUCLEO { get; set; }
        public string COGNOME { get; set; }
        public string NOME { get; set; }
        public string SESSO { get; set; }
        public string data_di_nascita { get; set; }
        public string COMUNE_DI_NASCITA { get; set; }
        public string PROVINCIA_DI_NASCITA { get; set; }
        public string INDIRIZZO { get; set; }
        public string CAP { get; set; }
        public string CITTA { get; set; }
        public string PROVINCIA { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public string DATA_INGRESSO_IN_POLIZZA { get; set; }
        public string DATA_USCITA_IN_POLIZZA { get; set; }
        public string IBAN { get; set; }
        public string DEN_INTESTATARIO_CONTO { get; set; }
        public string OPZIONE { get; set; }
        public string DATA_MODIFICA_OPZIONE { get; set; }
        public string PRESENZA_INTEGRATIVA { get; set; }
        public string PRESENZA_LTC { get; set; }
        public string CATEGORIA { get; set; }
        public string Expr1 { get; set; }
        public string ENTE { get; set; }
    }
}
