//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adesione
    {
        public long IdAdesione { get; set; }
        public string CodTipoAdesione { get; set; }
        public long IdCaponucleo { get; set; }
        public long IdSoggetto { get; set; }
        public string CodTipoSoggetto { get; set; }
        public string CodLegame { get; set; }
        public string FlagPagamentoEnte { get; set; }
        public string FlagPagamentoSoggetto { get; set; }
        public string StatoAdesione { get; set; }
        public string NumeroPratica { get; set; }
        public byte MeseDecorrenza { get; set; }
        public byte MeseScadenza { get; set; }
        public byte AnnoDecorrenza { get; set; }
        public byte AnnoScadenza { get; set; }
        public System.DateTime DataCessazione { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public System.DateTime DataAggiornamento { get; set; }
        public string CodiceUtente { get; set; }
        public string CodAppl { get; set; }
    
        public virtual Soggetto Soggetto { get; set; }
        public virtual Soggetto Soggetto1 { get; set; }
        public virtual T_StatoAdesione T_StatoAdesione { get; set; }
        public virtual T_TipiLegame T_TipiLegame { get; set; }
        public virtual T_TipoAdesione T_TipoAdesione { get; set; }
        public virtual T_TipoSoggetto T_TipoSoggetto { get; set; }
    }
}
