//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContribuzioneEnte
    {
        public long IdEnte { get; set; }
        public string CodTipoAdesione { get; set; }
        public System.DateTime DataInizioAdesione { get; set; }
        public Nullable<decimal> PercentualeQuota { get; set; }
        public Nullable<decimal> ValoreAssolutoQuota { get; set; }
        public string NumeroPolizza { get; set; }
        public System.DateTime DataFine { get; set; }
        public System.DateTime DataAggiornamento { get; set; }
        public string CodiceUtente { get; set; }
        public string CodAppl { get; set; }
    
        public virtual Ente Ente { get; set; }
        public virtual T_TipoAdesione T_TipoAdesione { get; set; }
    }
}
