//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ente
    {
        public Ente()
        {
            this.ContribuzioneEnte = new HashSet<ContribuzioneEnte>();
            this.EnteAppartenenza = new HashSet<EnteAppartenenza>();
        }
    
        public long IdEnte { get; set; }
        public string CodiceFiscale { get; set; }
        public string Progressivo { get; set; }
        public string RagioneSociale { get; set; }
        public string CodiceEnte { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public System.DateTime DataAggiornamento { get; set; }
        public string CodiceUtente { get; set; }
        public string CodAppl { get; set; }
    
        public virtual ICollection<ContribuzioneEnte> ContribuzioneEnte { get; set; }
        public virtual ICollection<EnteAppartenenza> EnteAppartenenza { get; set; }
        public virtual TipologiaEnte TipologiaEnte { get; set; }
    }
}
