//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModalitaPagamentoEnte
    {
        public long IdEnte { get; set; }
        public byte Anno { get; set; }
        public byte NumeroRate { get; set; }
        public decimal ImportoRata { get; set; }
    }
}
