//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemestriValidita
    {
        public byte Semestre { get; set; }
        public byte GiornoInizio { get; set; }
        public byte MeseInizio { get; set; }
        public byte GiornoFine { get; set; }
        public byte MeseFine { get; set; }
        public byte AddAnnoEffettoPerScadenza { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public System.DateTime DataAggiornamento { get; set; }
        public string CodiceUtente { get; set; }
        public string CodAppl { get; set; }
    }
}
