//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soggetto
    {
        public Soggetto()
        {
            this.Adesione = new HashSet<Adesione>();
            this.Adesione1 = new HashSet<Adesione>();
            this.EnteAppartenenza = new HashSet<EnteAppartenenza>();
            this.Soggetto1 = new HashSet<Soggetto>();
        }
    
        public long IdSoggetto { get; set; }
        public string CodiceFiscale { get; set; }
        public string Nome { get; set; }
        public string SecondoNome { get; set; }
        public string Cognome { get; set; }
        public System.DateTime DataNascita { get; set; }
        public string LuogoNascita { get; set; }
        public string IndirizzoResidenza { get; set; }
        public string ComuneResidenza { get; set; }
        public string SiglaProvinciaResidenza { get; set; }
        public string CapResidenza { get; set; }
        public string Email { get; set; }
        public string IBAN { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> DataModificaOpzione { get; set; }
        public Nullable<long> IdDanteCausa { get; set; }
        public string StatoRecord { get; set; }
        public string Fonte { get; set; }
        public string FonteModifica { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public Nullable<System.DateTime> DataAggiornamento { get; set; }
        public string CodiceUtente { get; set; }
        public string CodAppl { get; set; }
    
        public virtual ICollection<Adesione> Adesione { get; set; }
        public virtual ICollection<Adesione> Adesione1 { get; set; }
        public virtual ICollection<EnteAppartenenza> EnteAppartenenza { get; set; }
        public virtual ICollection<Soggetto> Soggetto1 { get; set; }
        public virtual Soggetto Soggetto2 { get; set; }
        public virtual T_StatoSoggetto T_StatoSoggetto { get; set; }
    }
}
