//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TariffarioAdesioniVolontarie
    {
        public string CodTipoAdesione { get; set; }
        public string CodTipoSoggetto { get; set; }
        public System.DateTime DataInizio { get; set; }
        public decimal QuotaProcapite { get; set; }
        public string CoperturaNucleoACarico { get; set; }
        public string CoperturaNucleoNonACarico { get; set; }
        public Nullable<decimal> QuotaProcapiteFAC { get; set; }
        public Nullable<decimal> QuotaProcapiteFNAC { get; set; }
        public System.DateTime DataFine { get; set; }
        public System.DateTime DataAggiornamento { get; set; }
        public string CodiceUtente { get; set; }
        public string CodAppl { get; set; }
    
        public virtual T_TipoAdesione T_TipoAdesione { get; set; }
        public virtual T_TipoSoggetto T_TipoSoggetto { get; set; }
    }
}
