//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TipiLegame
    {
        public T_TipiLegame()
        {
            this.Adesione = new HashSet<Adesione>();
            this.T_LimitiEta = new HashSet<T_LimitiEta>();
        }
    
        public string CodLegame { get; set; }
        public string DescLegame { get; set; }
        public string FlagCarico { get; set; }
        public string CodLegameImport { get; set; }
        public string CodLegameExport { get; set; }
        public string CodTipoCaricoExport { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public System.DateTime DataAggiornamento { get; set; }
        public string CodiceUtente { get; set; }
        public string CodAppl { get; set; }
    
        public virtual ICollection<Adesione> Adesione { get; set; }
        public virtual ICollection<T_LimitiEta> T_LimitiEta { get; set; }
    }
}
