//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TipoSoggetto
    {
        public T_TipoSoggetto()
        {
            this.Adesione = new HashSet<Adesione>();
            this.T_TariffarioAdesioniVolontarie = new HashSet<T_TariffarioAdesioniVolontarie>();
        }
    
        public string CodTipoSoggetto { get; set; }
        public string DescTipoSoggetto { get; set; }
        public string Opzione { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public System.DateTime DataAggiornamento { get; set; }
        public string CodiceUtente { get; set; }
        public string CodAppl { get; set; }
    
        public virtual ICollection<Adesione> Adesione { get; set; }
        public virtual ICollection<T_TariffarioAdesioniVolontarie> T_TariffarioAdesioniVolontarie { get; set; }
    }
}
