//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmministrazioneAsdep
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TipoAdesione
    {
        public T_TipoAdesione()
        {
            this.Adesione = new HashSet<Adesione>();
            this.ContribuzioneEnte = new HashSet<ContribuzioneEnte>();
            this.T_LimitiEta = new HashSet<T_LimitiEta>();
            this.T_TariffarioAdesioniVolontarie = new HashSet<T_TariffarioAdesioniVolontarie>();
            this.T_TipoAdesione1 = new HashSet<T_TipoAdesione>();
        }
    
        public string CodTipoAdesione { get; set; }
        public string DescBreve { get; set; }
        public string DescTipoAdesione { get; set; }
        public string CategoriaAdesione { get; set; }
        public string RifAdesioneCollettiva { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public System.DateTime DataAggiornamento { get; set; }
        public string CodiceUtente { get; set; }
        public string CodAppl { get; set; }
    
        public virtual ICollection<Adesione> Adesione { get; set; }
        public virtual ICollection<ContribuzioneEnte> ContribuzioneEnte { get; set; }
        public virtual T_CategoriaAdesione T_CategoriaAdesione { get; set; }
        public virtual ICollection<T_LimitiEta> T_LimitiEta { get; set; }
        public virtual T_TariffarioAdesioniCollettive T_TariffarioAdesioniCollettive { get; set; }
        public virtual ICollection<T_TariffarioAdesioniVolontarie> T_TariffarioAdesioniVolontarie { get; set; }
        public virtual ICollection<T_TipoAdesione> T_TipoAdesione1 { get; set; }
        public virtual T_TipoAdesione T_TipoAdesione2 { get; set; }
    }
}
